name: app-py
on:
  push
  
jobs:
  GitHub-to-Docker:
    name: GitHub Checkout
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3.3.0
      
      - name: build docker image
        run: docker build -t app-py-image .
        
     
      - name: tag docker image to build number
        run: docker tag app-py-image:latest ${{ secrets.DOCKER_REPO }}:${{ github.run_number }}
        
    
      - name: tag docker image to latest
        run: docker tag app-py-image:latest ${{ secrets.DOCKER_REPO }}:latest
        
   
      - name: login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      
    
      - name: push docker image with build number
        run: docker push ${{ secrets.DOCKER_REP30O }}:${{ github.run_number }}
       
    
      - name: push docker image with latest tag
        run: docker push ${{ secrets.DOCKER_REPO }}:latest
        
  Post-to-slack:
    name: posting to slack
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [GitHub-to-Docker]
    steps:
      - name: Post to a Slack channel
        id: slack
        uses: slackapi/slack-github-action@v1.23.0
        with:
          # Slack channel id, channel name, or user id to post message.
          # See also: https://api.slack.com/methods/chat.postMessage#channels
          # You can pass in multiple channels to post to by providing a comma-delimited list of channel IDs.
          channel-id: 'notifications'
          # For posting a simple plain text message
          slack-message: "GitHub build result: ${{ github.action_status }}\n${{ github.event.pull_request.html_url || github.event.head_commit.url }}"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        
      
